apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: skaffold-set-bug
profiles:
  - name: raw
    manifests:
      rawYaml:
        - k8s/base/resources.yaml
  - name: kustomize
    manifests:
      kustomize:
        paths:
          - k8s/overlays/prod
