apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: hello-app
resources:
  - ../../base
